name: Node build

on:
  pull_request:
    branches:
      - main

jobs:
  buildNPM:
    strategy:
      matrix:
        nodeVersion: [12, 14, 16]
    uses: aaronnickovich/common-workflows/.github/workflows/buildNPM.yaml@main
    with:
      nodeVersion: ${{ matrix.nodeVersion }}
